services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: selfhealing-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: selfhealing-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:29092,
        PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    container_name: selfhealing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: selfhealing
    ports:
      - "5432:5432"
    volumes:
      - selfhealing_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: selfhealing-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  spark-master:
    build: 
      context: "./"
      dockerfile: spark/Dockerfile
      
    image: apache/spark:3.4.1
    container_name: selfhealing-spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark:/opt/spark-apps
      - ./ml:/opt/ml
      - ./data:/opt/data

  spark-worker:
    build:
      context: "./"
      dockerfile: spark/Dockerfile
    image: apache/spark:3.4.1
    container_name: selfhealing-spark-worker
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8081:8081"
    volumes:
      - ./spark:/opt/spark-apps
      - ./ml:/opt/ml
      - ./data:/opt/data

  grafana:
    image: grafana/grafana:10.0.0
    container_name: selfhealing-grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - selfhealing_grafana_data:/var/lib/grafana

volumes:
  selfhealing_postgres_data:
  selfhealing_grafana_data: